name: Deploy APP2

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Deploy files via rsync
        run: |
          rsync -avz --delete \
            -e "ssh -o StrictHostKeyChecking=no" \
            ./ ubuntu@${{ secrets.SSH_HOST }}:${{ secrets.APP_DIR }}/

      - name: Set permissions (optional)
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} \
            "sudo chown -R www-data:www-data ${APP_DIR:-${{ secrets.APP_DIR }}} || true && sudo find ${APP_DIR:-${{ secrets.APP_DIR }}} -type d -exec chmod 755 {} \; && sudo find ${APP_DIR:-${{ secrets.APP_DIR }}} -type f -exec chmod 644 {} \;"

      - name: Reload nginx
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "sudo nginx -t && sudo systemctl reload nginx"
